Demo notebook for accomplishing Wednesday's goal for BW. This model is only technically better than mean baseline.

In [81]:
# Read New York City apartment rental listing data
import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import numpy as np


url = 'https://raw.githubusercontent.com/lukiepookieofficial/NYC-AirBNB/main/AB_NYC_2019.csv'
df = pd.read_csv(url)

In [82]:
#df = df.drop('price', axis=1)
df.head()

id  ... availability_365
0  2539  ...              365
1  2595  ...              355
2  3647  ...              365
3  3831  ...              194
4  5022  ...                0

[5 rows x 16 columns]

In [83]:
df.isnull().sum()

id                                    0
name                                 16
host_id                               0
host_name                            21
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       10052
reviews_per_month                 10052
calculated_host_listings_count        0
availability_365                      0
dtype: int64

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   id                              48895 non-null  int64  
 1   name                            48879 non-null  object 
 2   host_id                         48895 non-null  int64  
 3   host_name                       48874 non-null  object 
 4   neighbourhood_group             48895 non-null  object 
 5   neighbourhood                   48895 non-null  object 
 6   latitude                        48895 non-null  float64
 7   longitude                       48895 non-null  float64
 8   room_type                       48895 non-null  object 
 9   price                           48895 non-null  int64  
 10  minimum_nights                  48895 non-null  int64  
 11  number_of_reviews               48895 non-null  int64  
 12  last_review                     

In [85]:
df.describe()

id  ...  availability_365
count  4.889500e+04  ...      48895.000000
mean   1.901714e+07  ...        112.781327
std    1.098311e+07  ...        131.622289
min    2.539000e+03  ...          0.000000
25%    9.471945e+06  ...          0.000000
50%    1.967728e+07  ...         45.000000
75%    2.915218e+07  ...        227.000000
max    3.648724e+07  ...        365.000000

[8 rows x 10 columns]

In [86]:
#baseline 1
df.price.mean()

152.7206871868289

In [87]:
#amount of error based on baseline 1
guess = df.price.mean()
errors = guess - df.price
print(errors.abs().mean())

92.4510438837163


In [88]:
features = ['longitude', 'latitude', 'minimum_nights']
target = ['price']

x_train = df[features]
y_train = df[target]

In [89]:
X_train, X_test, y_train, y_test = train_test_split(x_train, y_train, test_size=0.25,
                                                    random_state=1138)
#Train random forest classification model
model = LinearRegression()
model.fit(X_train, y_train)
# Diagnosis prediction
y_predict = model.predict(X_test)

In [90]:
y_predict.mean()

152.78306321482944

In [91]:
#amount of error based on baseline 1
guess = y_predict.mean()
errors = guess - y_test
print(np.abs(errors).mean())

price    92.137886
dtype: float64


In [92]:
x_test = [[-73.94399, 1, 40.79851]]

y_pred = model.predict(x_test)
y_pred

array([[157.48528563]])

In [93]:
def prediction(lon, min_nights, lat):
  return model.predict([[ lon, min_nights , lat]])

In [94]:
prediction(-73.9425, 1, 40.7145)

array([[139.82004056]])

In [95]:
prediction(-73.9667, 2, 40.7947)

array([[175.34416142]])

In [96]:
model.coef_

array([[-7.99931112e+02,  4.39535282e-01,  1.96087938e+02]])